### ISSUE TITLE
Kanban Board Set up 

### ISSUE THREAD

**Issue by HunterX-7** [HunterX-7/Recipe-App#18]
### Link to the project

Please find below the link to our team project 🔗 
[Github Project](https://github.com/users/HunterX-7/projects/1).

## Members 👥 
In our team, we have 2 members: 

1. @HunterX-7 
2. @Dadadon

**Comment by prolajumokeoni** [comment]
HI @HunterX-7 and @Dadadon, Kindly make your GitHub project link(Kanban board) public so I can review
![Screenshot_10](https://user-images.githubusercontent.com/69638013/234044299-390ebeb4-51b2-45f3-a69b-12faf68be62a.png)

**Comment by HunterX-7** [comment]
Hi @prolajumokeoni, Sorry just made the requested change. You should be able to check it now. 😄

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
